Problem with multi-server mfiles
afcmrp/python-mfiles pull request #10
Opened 2023-05-22 16:32 UTC by barbyware

HI,

In case of multi-server environment you have to use cookie based sessions instead of authentication tokens:
https://m-files.com/APIs/REST-API/Authentication/#cookie-based-sessions

The solution is easy, create a request.Session and I use this change in all request.post call

2023-05-22 16:34 UTC, barbyware commented
In case of multi-server environment you have to use cookie based sessions instead of authentication tokens:
https://developer.m-files.com/APIs/REST-API/Authentication/#cookie-based-sessions

2023-05-22 17:32 UTC, afcmrp requested changes
Nicely done, left a few comments that should be resolved before merge.

2023-05-22 17:32 UTC, afcmrp commented on mfiles/client.py
> +        self.request = requests.Session()
This should be set in __init__ and I think a better name is self.session

2023-05-22 17:32 UTC, afcmrp commented on setup.py
> +    url='https://github.com/barbyware/python-mfiles',
This url should not change

2023-05-23 07:46 UTC, barbyware commented on setup.py
> +    url='https://github.com/barbyware/python-mfiles',
OK, you need that I made the changes or could be made yo

2023-05-23 08:23 UTC, closed without merging